---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: devacr.azurecr.io/backend:latest
          ports:
          - containerPort: 5001
          env:
          - name: DATABASE_NAME
            value: "mydb"
          - name: DATABASE_USER'
            value: "admin"
          - name: DATABASE_PASSWORD
            value: "P@ssword1"  # move it to secrets
          - name: DATABASE_HOST
            value: "pg_server.postgres.database.azure.com"
          - name: DATABASE_PORT
            value: "5432"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 8081
    targetPort: 5001