---
- name: Create PostgreSQL table and insert data
  hosts: pg_server.postgres.database.azure.com
  become: yes
  vars:
    db_name: mydb
    table_name: students
    db_user : admin
    db_password: '{{ lookup("env", "PASSWORD") }}'
    port: 5432
  tasks:
    - name: Ensure PostgreSQL database exists
      postgresql_db:
        name: "{{ db_name }}"
        login_user: "{{db_user}}"
        login_password: "{{ db_password}}"
        login_host: "{{ host}}"
        port: "{{port}}"
        state: present
    - name: Create PostgreSQL table
      postgresql_query:
        db: "{{ db_name }}"
        login_user: "{{db_user}}"
        login_password: "{{ db_password}}"
        login_host: "{{ host}}"
        port: "{{port}}"
        query: "CREATE TABLE IF NOT EXISTS {{ table_name }} (id SERIAL PRIMARY KEY,  name VARCHAR(100),address VARCHAR(255),city VARCHAR(100),pincode VARCHAR(20));"

    - name: Insert sample data into PostgreSQL table
      postgresql_query:
        db: "{{ db_name }}"
        login_user: "{{db_user}}"
        login_password: "{{ db_password}}"
        login_host: "{{ host}}"
        port: "{{port}}"
        query: "INSERT INTO {{ table_name }} (name, address, city, pincode) VALUES ('student1','address1','city1','1234'),('student2','address2','city2','5678');"
